"""
Card code → card name lookup.

data/card_names.json is generated by scripts/build_card_db.py, which reads
vendor/ygo-agent/scripts/code_list.txt. Re-run build_card_db.py after
`git submodule update` to pick up new cards.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_DEFAULT_PATH = Path(__file__).parent.parent.parent.parent / "data" / "card_names.json"


@lru_cache(maxsize=1)
def load_card_db(path: Path | None = None) -> dict[int, str]:
    p = path or _DEFAULT_PATH
    if not p.exists():
        return {}
    with open(p, encoding="utf-8") as f:
        raw: dict[str, str] = json.load(f)
    return {int(k): v for k, v in raw.items()}


def get_card_name(code: int, path: Path | None = None) -> str:
    if code == 0:
        return "unknown"
    db = load_card_db(path)
    return db.get(code, f"#{code}")
