"""
Card code → card name lookup.

data/card_names.json is generated by scripts/build_card_db.py, which reads
vendor/ygo-agent/scripts/code_list.txt. Re-run build_card_db.py after
`git submodule update` to pick up new cards.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_DEFAULT_NAMES_PATH = Path(__file__).parent.parent.parent.parent / "data" / "card_names.json"
_DEFAULT_INFO_PATH  = Path(__file__).parent.parent.parent.parent / "data" / "card_info.json"


@lru_cache(maxsize=1)
def load_card_db(path: Path | None = None) -> dict[int, str]:
    p = path or _DEFAULT_NAMES_PATH
    if not p.exists():
        return {}
    with open(p, encoding="utf-8") as f:
        raw: dict[str, str] = json.load(f)
    return {int(k): v for k, v in raw.items()}


@lru_cache(maxsize=1)
def load_card_info(path: Path | None = None) -> dict[int, dict]:
    p = path or _DEFAULT_INFO_PATH
    if not p.exists():
        return {}
    with open(p, encoding="utf-8") as f:
        raw: dict[str, dict] = json.load(f)
    return {int(k): v for k, v in raw.items()}


def get_card_name(code: int, path: Path | None = None) -> str:
    if code == 0:
        return "unknown"
    db = load_card_db(path)
    return db.get(code, f"#{code}")


def get_card_type(code: int) -> str:
    """Return 'spell', 'trap', or 'monster'. Defaults to 'monster' if unknown."""
    if code == 0:
        return "monster"
    info = load_card_info()
    return info.get(code, {}).get("card_type", "monster")


# card_info.json stores attribute as an integer YGOPro flag; map to ygoinf enum string
_ATTR_INT_TO_STR: dict[int, str] = {
    0: "none", 1: "earth", 2: "water", 4: "fire",
    8: "wind", 16: "light", 32: "dark", 64: "divine",
}


def card_from_db(
    code: int,
    controller: str = "me",
    location: str = "hand",
    position: str = "faceup_attack",
    sequence: int = 0,
) -> "Card":
    """Build a Card with real ATK/DEF/level/attribute from card_info.json."""
    from ygo_meta.engine.types import Card  # avoid circular import at module level
    info = load_card_info().get(code, {})
    attr = _ATTR_INT_TO_STR.get(info.get("attribute") or 0, "none")
    return Card(
        code=code,
        controller=controller,
        location=location,
        sequence=sequence,
        position=position,
        overlay_sequence=-1,
        attribute=attr,
        race="none",
        level=info.get("level") or 0,
        counter=0,
        negated=False,
        attack=info.get("atk") or 0,
        defense=info.get("def") or 0,
        types=[],
    )
